#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <fruit>" >&2
  exit 1
fi

fruit="$1"

case "$fruit" in
apple)
  echo "Has Apple"
  ;;
banana)
  echo "Has Banana"
  ;;
*)
  echo "$fruit is unknown" >&2
  exit 1
  ;;
esac
