apiVersion: v1
kind: Service
metadata:
  labels:
    app: rustical
  name: rustical
  namespace: calendar
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: rustical
  type: ClusterIP
  ipFamilyPolicy: SingleStack
